### PR TITLE
Combined generator

### PR DESCRIPTION
**Pull request by jaredbro**
Adds a new generator that combines the calls to common app, ios, and android into a single command.

This is the first of 2 changes.  This change adds the new generator and moves all the shared data and prompts to a new common.js file.  This also renames the old app generator to common, and uses the new combined app for the new generator.  After this change is reviewed and merged, I will refactor the other generators so there is no duplication of prompts and shared data in the individual generators.

### CODE REVIEW

**Comment by michaeldeol** [comment]
Three things I noticed:

1. I find the following question confusing from a new developer to liger `? What would you like to use as the Class Prefix for all native classes? ()`
2. This question was confusing as it only let me select one option `? What mobile platforms do you want to support? iOS, Android`
3. I received the following error `Unhanded 'error' event` screenshot below

screenshot 2015-03-13 14 52 23

**Comment by jaredbro** [comment]
@michaeldeol Thanks for giving it a try!

1. I'll have to defer to @ligerjohn on a better wording for this.  This is VERY specific to Objective-C, and he would be better at refining that question than I would be.  Maybe there isn't a better way to word it and you just have to know it to use it?

2.  Weird, it is supposed to display a set of "checkboxes" that you can use the arrow keys to move the highlighted one and then use the spacebar to select or unselect values.  See the screenshot below, where I have put the focus on "Android" and unselected it.  Does it not look like this for you?

3. Did you run 'npm install' before running the generator?  That is a requirement to use it when checking out from github.

image

**Comment by gary-moon** [comment]
I ran into an issue with the json gem, but I fixed it by running `rum gemset empty` and reran the generator.

I ran the same thing Michael did, and an application was successfully generated.

**Pull request merged**
