### PR TITLE
Updates that corresponds to the new version of liger-common

### PR DESCRIPTION
**Pull request by ligerjohn**
Fixed paths
Added in use of bootstrap icons
Pulling from master instead of requirejs for common-liger
Added prettify for the templates (easier to debug)

IMPORTANTE! If anyone wants to test the code out, you need to switch back from #master to #requirejs until the reachlocal/liger-common PR has been merged.

### CODE REVIEW

**Comment by michaeldeol** [comment]
When I run `yo ligermobile` I am getting the following error:
```sh
Error: Cannot find module 'gulp-js-prettify'
```
I ran `npm install` within my test generated app and within generator-ligermobile with no luck. Am I simply forgetting a step?

**Comment by michaeldeol** [comment]
Looks like we need to add `"gulp-js-prettify": "^0.1.0"` to `generators/app/templates/_package.json` and this should resolve the error I was getting.

**Comment by ligerjohn** [comment]
Fixed the b0rked gulp-js-prettify mistake.

**Comment by michaeldeol** [comment]
:+1:

**Comment by markleppke** [comment]
Let's use "gulp-js-prettify": "0.1.0" vs "gulp-js-prettify": "^0.1.0"...

things can get messy if we choose x or newer... things break for people if we don't manage upgrading our plugins

**Pull request merged**
